# Generated by Django 5.1.6 on 2025-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('skin_type', models.CharField(choices=[('Normal', 'Normal'), ('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination'), ('Sensitive', 'Sensitive')], max_length=20)),
                ('skin_issues', models.TextField()),
            ],
        ),
    ]
